import { useState } from 'react';
import { Modal } from '../shared/Modal';
import { Button } from '../shared/Button';
import { db, Meeting, Minute, ActionItem } from '../../db/database';

interface Props {
  open: boolean;
  onClose: () => void;
  meeting: Meeting;
  minute: Minute;
}

export function ExportModal({ open, onClose, meeting, minute }: Props) {
  const [style, setStyle] = useState<'kpi-driven' | 'contextual-report'>('kpi-driven');

  const generateKpiHtml = () => {
    const items = minute.actionItems;
    const rows = items.map((item) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #30363d">${item.action}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #30363d;white-space:nowrap">${item.owner}${item.department ? ` (${item.department})` : ''}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #30363d;color:${priColor(item.priority)};font-weight:600">${item.priority}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #30363d;color:${riskColor(item.riskLevel)}">${item.riskLevel}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #30363d">${item.ownerConfirmed ? 'Confirmed' : 'Unconfirmed'}</td>
      </tr>
    `).join('');

    return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Meeting Minutes — ${meeting.title}</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#0d1117;color:#e6edf3;padding:40px;max-width:960px;margin:0 auto}
h1{font-size:22px;margin-bottom:4px}h2{font-size:14px;color:#8b949e;margin-bottom:24px}
table{width:100%;border-collapse:collapse;font-size:14px}th{text-align:left;padding:8px 12px;font-size:12px;color:#8b949e;text-transform:uppercase;border-bottom:2px solid #30363d}
.meta{display:flex;gap:20px;margin-bottom:24px;font-size:13px;color:#8b949e}
</style></head><body>
<h1>${meeting.title}</h1>
<h2>Meeting Minutes — ${new Date(meeting.uploadedAt).toLocaleString('zh-CN')}</h2>
<div class="meta"><span>Sentiment: ${meeting.metadata.sentimentScore?.toFixed(2) ?? 'N/A'}</span><span>Actions: ${items.length}</span><span>Track: ${meeting.metadata.trackUsed ?? 'N/A'}</span></div>
<table><thead><tr><th>Action</th><th>Owner</th><th>Priority</th><th>Risk</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>
<p style="font-size:11px;color:#6e7681;margin-top:24px">Generated by AI Execution Pocket v1.1.0</p>
</body></html>`;
  };

  const generateReportHtml = () => {
    const items = minute.actionItems;
    const sections = items.map((item) => `
      <div style="margin-bottom:20px;padding:16px;background:#161b22;border-radius:8px;border-left:3px solid ${priColor(item.priority)}">
        <h3 style="margin:0 0 8px;font-size:15px">${item.action}</h3>
        <p style="margin:0 0 6px;font-size:13px;color:#8b949e">Owner: <strong style="color:#e6edf3">${item.owner}</strong> · Priority: <strong style="color:${priColor(item.priority)}">${item.priority}</strong> · Risk: <strong style="color:${riskColor(item.riskLevel)}">${item.riskLevel}</strong></p>
        ${item.deadlineHint ? `<p style="margin:0 0 6px;font-size:13px;color:#8b949e">Deadline: ${item.deadlineHint}</p>` : ''}
        ${item.contextAnchor ? `<blockquote style="margin:8px 0 0;padding:8px 12px;background:#0d1117;border-radius:4px;font-size:12px;color:#8b949e;border-left:2px solid #58a6ff">"${item.contextAnchor}"</blockquote>` : ''}
        <p style="margin:8px 0 0;font-size:12px;color:#6e7681">Status: ${item.ownerConfirmed ? 'Owner Confirmed' : 'Pending Confirmation'} · Source: ${item.trackSource}</p>
      </div>
    `).join('');

    return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Meeting Report — ${meeting.title}</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#0d1117;color:#e6edf3;padding:40px;max-width:800px;margin:0 auto;line-height:1.6}
h1{font-size:24px;margin-bottom:4px}h2{font-size:15px;color:#8b949e;margin-bottom:8px}
.context{font-size:13px;color:#8b949e;margin-bottom:28px;padding:16px;background:#161b22;border-radius:8px}
</style></head><body>
<h1>${meeting.title}</h1>
<h2>Meeting Minutes Report</h2>
<div class="context"><strong>Date:</strong> ${new Date(meeting.uploadedAt).toLocaleString('zh-CN')}<br>
<strong>Sentiment:</strong> ${meeting.metadata.sentimentScore?.toFixed(2) ?? 'N/A'} · <strong>Track:</strong> ${meeting.metadata.trackUsed ?? 'N/A'}<br>
<strong>Actions:</strong> ${items.length} items identified</div>
${sections}
<p style="font-size:11px;color:#6e7681;margin-top:32px">Generated by AI Execution Pocket v1.1.0</p>
</body></html>`;
  };

  const handleExport = async (format: 'html-download' | 'clipboard' | 'print-pdf') => {
    const html = style === 'kpi-driven' ? generateKpiHtml() : generateReportHtml();

    if (format === 'print-pdf') {
      const w = window.open('', '_blank', 'width=900,height=700');
      if (w) {
        w.document.write(html);
        w.document.close();
        w.onload = () => { w.focus(); w.print(); };
      }
    } else if (format === 'html-download') {
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${meeting.title.replace(/[^a-zA-Z0-9一-鿿]/g, '_')}_${style}.html`;
      a.click();
      URL.revokeObjectURL(url);
    } else {
      await navigator.clipboard.writeText(html);
    }

    // Track export
    if (minute.id) {
      const exportHistory = minute.exportHistory || [];
      exportHistory.push({ exportedAt: Date.now(), style, format });
      await db.minutes.update(minute.id, { exportHistory });
    }
  };

  return (
    <Modal open={open} onClose={onClose} title="Export Meeting Minutes" width={600}>
      <div className="export-styles" style={{ display: 'flex', gap: 10, marginBottom: 24 }}>
        <StyleCard
          title="KPI-Driven Table"
          description="Cold, hard facts. Direct owner/deadline/risk table. Best for executives and cross-functional tracking."
          selected={style === 'kpi-driven'}
          onClick={() => setStyle('kpi-driven')}
        />
        <StyleCard
          title="Contextual Report"
          description="Narrative style with background and context. Best for weekly reports and archival."
          selected={style === 'contextual-report'}
          onClick={() => setStyle('contextual-report')}
        />
      </div>

      <div style={{ maxHeight: 300, overflow: 'auto', background: 'var(--bg-primary)', borderRadius: 'var(--radius-md)', padding: 16, marginBottom: 20 }}>
        <div dangerouslySetInnerHTML={{ __html: style === 'kpi-driven' ? generateKpiHtml() : generateReportHtml() }}
          style={{ transform: 'scale(0.75)', transformOrigin: 'top left', width: '133%' }} />
      </div>

      <div className="export-btns" style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
        <Button variant="secondary" size="sm" onClick={() => handleExport('clipboard')}>
          Copy
        </Button>
        <Button variant="secondary" size="sm" onClick={() => handleExport('print-pdf')}>
          Print to PDF
        </Button>
        <Button size="sm" onClick={() => handleExport('html-download')}>
          Download HTML
        </Button>
      </div>

      <style>{`
        @media (max-width: 768px) {
          .export-styles { flex-direction: column !important; }
          .export-btns { flex-wrap: wrap !important; }
          .export-btns button { flex: 1; min-width: 80px; }
        }
      `}</style>
    </Modal>
  );
}

function StyleCard({ title, description, selected, onClick }: { title: string; description: string; selected: boolean; onClick: () => void }) {
  return (
    <div
      onClick={onClick}
      style={{
        flex: 1, padding: 14, borderRadius: 'var(--radius-md)', cursor: 'pointer',
        background: selected ? 'rgba(88,166,255,0.08)' : 'var(--bg-tertiary)',
        border: `2px solid ${selected ? 'var(--accent-blue)' : 'var(--border-default)'}`,
        transition: 'all 0.15s',
      }}
    >
      <div style={{ fontWeight: 700, fontSize: 13, marginBottom: 4 }}>
        {selected && <span style={{ color: 'var(--accent-blue)', marginRight: 6 }}>●</span>}
        {title}
      </div>
      <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.5 }}>{description}</div>
    </div>
  );
}

function priColor(p: string) {
  return { P0: '#f85149', P1: '#d2991d', P2: '#58a6ff', P3: '#8b949e' }[p] || '#8b949e';
}

function riskColor(r: string) {
  return { high: '#f85149', medium: '#d2991d', low: '#3fb950' }[r] || '#8b949e';
}

